services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: mobile@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "80:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  arshopping:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres_data:
  pgadmin_data:
